import type { Product } from "@shared/products";

/**
 * Last-known-good public catalog snapshot.
 *
 * Only products verified as active=true + workflow_status=PUBLISHED + qa_status=PASS
 * are included. Live API / edge mirror / published Google Sheet remain authoritative
 * and are attempted first. The snapshot prevents a temporary Cloudflare/upstream
 * outage from collapsing the storefront to an empty catalog.
 *
 * Source of truth: Omran Trading Master Database / products sheet.
 * Visual QA expanded on 2026-09-03 for OMR-RAW-001..005.
 */
export const PUBLIC_PRODUCTS_SNAPSHOT: Product[] = [
  {
    id: "OMR-IG-KIT-46",
    name: "مطبخ ألعاب للأطفال — 46 قطعة",
    price: 850,
    category: "ألعاب مطبخ",
    description:
      "مطبخ أطفال كامل بأدوات وأواني وإكسسوارات كثيرة للعب التخيلي مناسب للبنات والأولاد. تنبيه أمان: يُستخدم تحت إشراف الكبار حسب العمر الموصى به.",
    image: "/products/processed/product-kitchen-46pcs-main.webp",
    imageSource: "/products/processed/product-kitchen-46pcs-main.webp",
    active: true,
    sortOrder: 2,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: null,
    processedImage: "/products/processed/product-kitchen-46pcs-main.webp",
    reviewReason: null,
    rowIndex: 1,
  },
  {
    id: "OMR-IG-HC-104",
    name: "مطبخ Home Chef للأطفال — 104 قطعة",
    price: 1850,
    category: "ألعاب مطبخ",
    description:
      "مطبخ لعب واقعي جدًا بإضاءة وأصوات وملحقات كثيرة مناسب للأطفال من 3 سنوات. تنبيه أمان: يُستخدم تحت إشراف الكبار حسب العمر الموصى به.",
    image: "/products/processed/product-home-chef-104pcs-main.webp",
    imageSource: "/products/processed/product-home-chef-104pcs-main.webp",
    active: true,
    sortOrder: 3,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: null,
    processedImage: "/products/processed/product-home-chef-104pcs-main.webp",
    reviewReason: null,
    rowIndex: 2,
  },
  {
    id: "OMR-IG-SQ-01",
    name: "لعبة الاسكوشي بأشكال وألوان متنوعة",
    price: 275,
    category: "فنون وإبداع وصلصال",
    description:
      "لعبة ناعمة ولطيفة للتسلية وتفريغ الطاقة تنفع كهدية حلوة للأطفال والكبار. تنبيه أمان: غير مناسبة للأطفال أقل من 3 سنوات لاحتوائها على أجزاء صغيرة.",
    image: "/products/processed/product-ot-00001-main.webp",
    imageSource: "/products/processed/product-ot-00001-main.webp",
    active: true,
    sortOrder: 4,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: null,
    processedImage: "/products/processed/product-ot-00001-main.webp",
    reviewReason: null,
    rowIndex: 3,
  },
  {
    id: "OMR-RAW-001",
    name: "محلول فقاعات صابون",
    price: null,
    category: "ألعاب خارجية وفقاعات",
    description:
      "محلول فقاعات صابون للأطفال بعبوة 250 مل كما هو ظاهر على العبوة، مناسب لألعاب الفقاعات والأنشطة الخارجية.",
    image: "https://drive.google.com/thumbnail?id=1dtiEbbptINTXxtQAwpkKpI2fxBAxYbLm&sz=w1000",
    imageSource: "https://drive.google.com/uc?export=view&id=1dtiEbbptINTXxtQAwpkKpI2fxBAxYbLm",
    active: true,
    sortOrder: 5,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: "1I_QGGoYTxq7zdfd5UgWFReB7MS9Tg36U",
    processedImage: "https://drive.google.com/uc?export=view&id=1dtiEbbptINTXxtQAwpkKpI2fxBAxYbLm",
    reviewReason: null,
    rowIndex: 4,
  },
  {
    id: "OMR-RAW-002",
    name: "حقيبة رسم وتلوين زرقاء",
    price: null,
    category: "ألعاب تعليمية وفنية",
    description:
      "حقيبة رسم وتلوين زرقاء تضم مجموعة متنوعة من أقلام التلوين والألوان وأدوات الرسم مرتبة داخل حقيبة.",
    image: "https://drive.google.com/thumbnail?id=1ORWMwfpwHgF-Usqg1oBvzCx4FIVhj18T&sz=w1000",
    imageSource: "https://drive.google.com/uc?export=view&id=1ORWMwfpwHgF-Usqg1oBvzCx4FIVhj18T",
    active: true,
    sortOrder: 6,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: "1Sdozgd1CS2oAtJcUN-fjIhQzmAq_AuVl",
    processedImage: "https://drive.google.com/uc?export=view&id=1ORWMwfpwHgF-Usqg1oBvzCx4FIVhj18T",
    reviewReason: null,
    rowIndex: 5,
  },
  {
    id: "OMR-RAW-003",
    name: "حقيبة رسم وتلوين وردية",
    price: null,
    category: "ألعاب تعليمية وفنية",
    description:
      "حقيبة رسم وتلوين وردية تضم مجموعة متنوعة من أقلام التلوين والألوان وأدوات الرسم مرتبة داخل حقيبة.",
    image: "https://drive.google.com/thumbnail?id=13TDSnLvR07wTBesPQcHb6jTZYtjIxwKT&sz=w1000",
    imageSource: "https://drive.google.com/uc?export=view&id=13TDSnLvR07wTBesPQcHb6jTZYtjIxwKT",
    active: true,
    sortOrder: 7,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: "1pM9lcH17V7pCw9l_6_hC4hPrPoDCNZVn",
    processedImage: "https://drive.google.com/uc?export=view&id=13TDSnLvR07wTBesPQcHb6jTZYtjIxwKT",
    reviewReason: null,
    rowIndex: 6,
  },
  {
    id: "OMR-RAW-004",
    name: "بيانو أطفال بشكل كلب",
    price: null,
    category: "ألعاب موسيقية",
    description:
      "بيانو أطفال بتصميم كلب لطيف مع مفاتيح موسيقية وعناصر تفاعلية ظاهرة بالعبوة.",
    image: "https://drive.google.com/thumbnail?id=1SZxh2FDS3GOpt9RkBDdg9R1Vv0ecI4oZ&sz=w1000",
    imageSource: "https://drive.google.com/uc?export=view&id=1SZxh2FDS3GOpt9RkBDdg9R1Vv0ecI4oZ",
    active: true,
    sortOrder: 8,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: "16HLRBn8l6aRKSTnE17sDyfaZNSFNC-cP",
    processedImage: "https://drive.google.com/uc?export=view&id=1SZxh2FDS3GOpt9RkBDdg9R1Vv0ecI4oZ",
    reviewReason: null,
    rowIndex: 7,
  },
  {
    id: "OMR-RAW-005",
    name: "Rabbit Piano بيانو أطفال",
    price: null,
    category: "ألعاب موسيقية",
    description:
      "Rabbit Piano للأطفال بتصميم أرنب، يضم مفاتيح موسيقية وعناصر تفاعلية كما هو ظاهر على العبوة.",
    image: "https://drive.google.com/thumbnail?id=1z_jLgW6E1cOc8TVxImwf8qb7POrcQC8b&sz=w1000",
    imageSource: "https://drive.google.com/uc?export=view&id=1z_jLgW6E1cOc8TVxImwf8qb7POrcQC8b",
    active: true,
    sortOrder: 9,
    productPrompt: "",
    workflowStatus: "PUBLISHED",
    qaStatus: "PASS",
    sourceDriveId: "1YTUycmB_vORBD4n29HkhZoZ1vpxJT29y",
    processedImage: "https://drive.google.com/uc?export=view&id=1z_jLgW6E1cOc8TVxImwf8qb7POrcQC8b",
    reviewReason: null,
    rowIndex: 8,
  },
];
