import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse } from "dotenv";
import { fetchProductsPayload, isPubliclyVisible, type Product } from "../shared/products";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_FILE = resolve(ROOT, ".env.production");
const OUTPUT_FILE = resolve(ROOT, "client/src/lib/publicProductsSnapshot.ts");

async function readSheetUrl(): Promise<string> {
  const envText = await readFile(ENV_FILE, "utf8");
  const fileEnv = parse(envText);
  const url =
    process.env.PRODUCTS_SHEET_URL ||
    process.env.VITE_PRODUCTS_SHEET_URL ||
    process.env.NEXT_PUBLIC_PRODUCTS_SHEET_URL ||
    fileEnv.PRODUCTS_SHEET_URL ||
    fileEnv.VITE_PRODUCTS_SHEET_URL ||
    fileEnv.NEXT_PUBLIC_PRODUCTS_SHEET_URL ||
    "";

  if (!url) {
    throw new Error("Public products sheet URL is not configured");
  }
  return url;
}

function validateProducts(products: Product[]): void {
  if (products.length === 0) {
    throw new Error("Refusing to generate an empty public storefront snapshot");
  }

  const ids = new Set<string>();
  for (const product of products) {
    if (!isPubliclyVisible(product)) {
      throw new Error(`Publication gate violation in snapshot: ${product.id}`);
    }
    if (!product.id.trim()) {
      throw new Error("Snapshot contains a product without an ID");
    }
    if (ids.has(product.id)) {
      throw new Error(`Duplicate public product ID: ${product.id}`);
    }
    ids.add(product.id);

    if (!product.image) {
      throw new Error(`Public product has no displayable image: ${product.id}`);
    }
  }
}

function renderSnapshot(products: Product[]): string {
  const serialized = JSON.stringify(products, null, 2);
  return `import type { Product } from "@shared/products";\n\n/**\n * AUTO-GENERATED last-known-good public catalog snapshot.\n *\n * Source: Omran Trading Master Database / published products CSV.\n * Generator: scripts/generate-public-products-snapshot.ts\n * Gate: active=true + workflow_status=PUBLISHED + qa_status=PASS.\n *\n * Do not edit this file manually. Production CI refreshes it before tests/build.\n */\nexport const PUBLIC_PRODUCTS_SNAPSHOT: Product[] = ${serialized} as Product[];\n`;
}

async function main() {
  const sheetUrl = await readSheetUrl();
  const payload = await fetchProductsPayload(sheetUrl, (url, init) => fetch(url, init), {
    timeoutMs: 20_000,
  });

  if (payload.status !== "ok") {
    throw new Error(`Products source is not healthy: ${payload.status}`);
  }

  validateProducts(payload.products);
  await writeFile(OUTPUT_FILE, renderSnapshot(payload.products), "utf8");

  console.log(
    `Generated public storefront snapshot: ${payload.products.length} verified products`
  );
}

main().catch(error => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exitCode = 1;
});
